### ISSUE TITLE
Randomly has (MISSING) inserted into the password.

### ISSUE THREAD

**Issue by TerminalFi** [sethvargo/go-password#11]
Issues generating passwords. Appears that occasionally the password is generated incorrectly.

Can't determine issue. I've tried with bash, sh, zsh

<img width="511" alt="Alt" src="https://user-images.githubusercontent.com/32599364/68090057-7885b700-fe3d-11e9-918c-15dc9ff22a1a.png">

**Comment by sethvargo** [comment]
Hi @TheSecEng 

Thank you for opening an issue. Can you help me understand what this image is showing? Are you referring to 12:24:04 line 2? Can you share your script with me please?

**Comment by sethvargo** [comment]
My best guess is that you're doing this:

```go
log.Printf(myPassword)
```

When the generator generates a password, it might include special characters depending on your settings, including the `%` character, which has a special meaning in string formatting. If you get unlucky and get a password like:

```text
abcd%sdajkl
```

The `%s` in that is interpreted as string interpolation and expects a value to the variadic `Printf` function. Since no value is given, it inserts `(MISSING)`.

This is not a bug in go-password, this is how string formatting works in Go (and other languages).

You should either use `Print` instead of `Printf`, or use `Printf` like this:

```go
log.Printf("%s", myPassword)
```
